[package]
name = "sabre-lang"
version = "0.2.1"
authors = ["Garrit Franke <garrit@slashdev.space>"]
description = "The sabre programming language"
license = "Apache-2.0"
documentation = "https://garritfra.github.io/sabre"
repository = "https://github.com/garritfra/sabre"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "sabre"
path = "src/main.rs"

[features]
backend_c = []
backend_node = []
backend_llvm = ["inkwell"]

# To change, use the --featues flag:
# cargo run --features backend_llvm
default = ["backend_node"]

[dependencies]
structopt = "0.3.21"
rust-embed = "5.7.0"
tempfile = "3.1.0"
inkwell = { version = "0.1.0-beta.2", features = ["llvm10-0"], optional = true }

