[package]
name = "antimony-lang"
version = "0.5.1"
authors = ["Garrit Franke <garrit@slashdev.space>"]
description = "The Antimony programming language"
license = "Apache-2.0"
documentation = "https://antimony-lang.github.io/antimony"
repository = "https://github.com/antimony-lang/antimony"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "sb"
path = "src/main.rs"

[dependencies]
structopt = "0.3.21"
rust-embed = "5.7.0"
tempfile = "3.1.0"
inkwell = { version = "0.1.0-beta.2", features = ["llvm10-0"] }

