[package]
name = "sabre-lang"
version = "0.1.0"
authors = ["Garrit Franke <garrit@slashdev.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
backend_c = []
backend_node = []

default = ["backend_node"]

[dependencies]
structopt = "0.3.21"
rust-embed = "5.7.0"
tempfile = "3.1.0"
