[package]
name = "sabre-lang"
version = "0.2.0"
authors = ["Garrit Franke <garrit@slashdev.space>"]
description = "The sabre programming language"
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "sabre"
path = "src/main.rs"

[features]
backend_c = []
backend_node = []

default = ["backend_node"]

[dependencies]
structopt = "0.3.21"
rust-embed = "5.7.0"
tempfile = "3.1.0"
