[package]
name = "sabre"
version = "0.0.1"
authors = ["Garrit Franke <garritfranke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
backend_c = []
backend_node = []

default = ["backend_c"]

[dependencies]
structopt = "0.3.21"
rust-embed = "5.7.0"